### ISSUE TITLE
Add Adobe Digital Editions Installer

### ISSUE THREAD

**Issue by ntnsndr** [bottlesdevs/programs#10]
ADE is a program necessary to access DRM-protected ebooks from many retailers, and it is not available on Linux natively. I have tried to use Bottles to install it but have repeatedly encountered errors with dependencies that I can't figure out, as someone with very little experience with Windows. It would be really helpful if someone who figures out the right formula to share this as an installer. Thanks so much in advance!

**Comment by mirkobrombin** [comment]
I don't know if I will be able to do it myself but I will try for sure

**Comment by ntnsndr** [comment]
Thank you!

Nov 15, 2021 12:03:26 AM Mirko Brombin ***@***.***>:

**Comment by ntnsndr** [comment]
Wow, great news! Thank you so much! When will the release be on flatpak?
