### ISSUE TITLE
[Bug]: Unity Hub doesn't get the auth callback.

### ISSUE THREAD

**Issue by Kirbyrawr** [bottlesdevs/programs#103]
### Describe the bug

If you are trying to log in UnityHub using Bottles, it opens your linux browser, it tells you to select the program (you need to have it added before to desktop via Bottles) then it does nothing, it seems the callback is not getting to the app running with Bottles.

### To Reproduce

1. Create a Bottle
2. Install UnityHub (Download from Unity webpage)
3. Run the installer.
4. When it finish, open UnityHub
5. Try to login.
6. It doesn't get the callback response.

### Package

Flatpak from Flathub

### Distribution

Steam OS

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 10.1GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Unity is native on Linux. I’ve already tried to make it works under wine (for testing purpose) and always getting a bad experience. I suggest you to use the native version if possible (there is a flatpak too)

**Comment by Kirbyrawr** [comment]
The problem is that Unity under flatpak is ok but when you are trying to use Visual Studio Code with an inmutable distro like Steam OS you can't get Omnisharp to work (intellisense) because you need to install Mono with MSBuild but it's not available under Flatpak. 

This was just a workaround for that.

**Comment by mirkobrombin** [comment]
That makes sense. You can try asking in the flathub mono repository to provide this.

As a workaround you can try installing a web browser inside the bottle. Firefox should works

**Comment by Kirbyrawr** [comment]
> That makes sense. You can try asking in the flathub mono repository to provide this.
> 
> As a workaround you can try installing a web browser inside the bottle. Firefox should works

Appreciate, thank you very much.
