### ISSUE TITLE
[Bug]: Can't launch some games from Battle

### ISSUE THREAD

**Issue by rjousse18** [bottlesdevs/programs#108]
### Describe the bug

When I launch some games directly after I installed Battle. Hearthstone works but not Diablo Immortal and Heroes Of The Storm. Same issue with Soda and Caffe. I can't get logs from battle net.

### To Reproduce

1 Create bottle with caffe or soda
2 Install Battle from Installation Program
3 Install Diablo Immortal or HoTS

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.11-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8271532032
    Free: 8271384576
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 10.0GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Can you provide some logs?

**Comment by rjousse18** [comment]
How can I do that ? When I have the wine crash report window, it crash

**Comment by mirkobrombin** [comment]
start bottles from terminal, then start the game and check the output

**Comment by rjousse18** [comment]
This is all logs when I launch Diablo Immortal

09:37:12 (INFO) Bottles Started! 
09:37:14 (INFO) Catalog components loaded 
09:37:14 (INFO) Catalog installers loaded 
09:37:14 (INFO) Catalog dependencies loaded 
09:37:14 (INFO) Performing Bottles checks… 
09:37:14 (INFO) Dxvks found:
	 - dxvk-1.10.1
 
09:37:14 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6
 
09:37:14 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
09:37:14 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
09:37:14 (INFO) Runners found:
	 - sys-wine-7.0
	 - caffe-7.7
	 - soda-7.0-2
 
09:37:14 (INFO) Bottles found:
	 - Battle
 
09:37:14 (INFO) Library saved 
09:37:17 (INFO) No states found for bottle: [Battle] 

(bottles:2): Gtk-WARNING **: 09:37:17.515: Failed to set text 'Fusion 360 is a cloud-based 3D CAD, CAM & CAE design tool from Autodesk. It is available on a number of platforms including Windows, Mac & In-Browser.' from markup due to error parsing markup: Erreur à la ligne 1 : L’entité ne se termine pas par un point-virgule ; vous avez probablement utilisé une esperluette sans intention d’écrire une entité — échappez l’esperluette avec &amp;

(bottles:2): Gdk-CRITICAL **: 09:37:17.996: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:18.080: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT (event)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:19.600: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:20.063: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT (event)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:20.616: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:20.690: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT (event)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:23.289: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:23.324: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed
09:37:23 (INFO) Launching an executable… 
09:37:23 (WARNING) Windows path detected. Avoiding validation. 
09:37:23 (INFO) Using Wine Starter -- run 
09:37:23 (INFO) Using Bottles runtime 
09:37:23 (INFO) Using EasyAntiCheat runtime 
09:37:23 (INFO) Using BattlEye runtime 
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

0158:err:ole:com_get_class_object apartment not initialised
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0


(bottles:2): Gdk-CRITICAL **: 09:37:33.097: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT_TYPE (event, GDK_SCROLL)' failed

(bottles:2): Gdk-CRITICAL **: 09:37:33.183: gdk_scroll_event_get_direction: assertion 'GDK_IS_EVENT (event)' failed
0210:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x200e6
0258:err:esync:__esync_wait_objects Polling on fd 173 returned 0x20.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0508), starting debugger...

**Comment by TheoCGaming** [comment]
> wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0508), starting debugger...

"starting debugger..."
Can you get any debug output from WINE, file or otherwise?

**Comment by mirkobrombin** [comment]
Which runner is using?

**Comment by rjousse18** [comment]
> > wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0508), starting debugger...
> 
> "starting debugger..." Can you get any debug output from WINE, file or otherwise?

When I click on the button "see logs" from debugger window, it crash :/



> Which runner is using?

soda 7.0-2, I tried caffe 7.7 too
