### ISSUE TITLE
[Bug]: Epic Games Launcher crashes due to driver version on Arch

### ISSUE THREAD

**Issue by TheoCGaming** [bottlesdevs/programs#109]
### Describe the bug

The Epic Games Launcher crashes on startup due to a "problem with your graphics card" after it updates from the initial install. It was installed via the installer package.

### To Reproduce

0: Ensure you have a GTX 960 or similar card to test with.
1: Install the Epic Games Launcher via the installer package.
2: Let the launcher update.
3: The launcher will show a popup error saying: "There is a problem with your graphics card. Please ensure your card meets the minimum system requirements and that you have the latest drivers installed."

### Package

AUR ("bottles" package)

### Distribution

Arch Linux, installed from June 2022 ISO

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.11-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 20744196096
    Free: 2985242624
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Graphics card: GM206 (GTX 960)
Graphics Drivers: Latest proprietary NVIDIA drivers
CPU: i3 550 (maybe it's pulling from that? but I don't think I even have _drivers_ for the integrated GPU.)
Runner: Soda with Steam runtime, although I saw the same behavior with the standard WINE runner.
Uses: DXVK, VKD3D, and DLSS

**Comment by TheoCGaming** [comment]
oh cool, the flatpak release kept the AUR version's stuff

**Comment by TheoCGaming** [comment]
also the issue still persists

**Comment by mirkobrombin** [comment]
It shouldn’t take your old data, uses its own path. Can you post a new health check?

**Comment by TheoCGaming** [comment]
```
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.11-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 20744196096
    Free: 3284656128
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 9.0GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

**Comment by TheoCGaming** [comment]
note: bottles was *already uninstalled* with `yay -R bottles` and reinstalled using GNOME Software. (ironic being on XFCE.)

**Comment by TheoCGaming** [comment]
launcher info on Docklike Taskbar shows `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bottles --file-forwarding com.usebottles.bottles @@u %u @@`

**Comment by mirkobrombin** [comment]
Seems like you exposed host permissions to the flatpak, so it will use your system libraries. Reset permissions using flatseal. 


anyway this problem is system related for sure, I don’t think it is something that bottles can fix (I’m also unable to replicate)

**Comment by TheoCGaming** [comment]
restarted session, fixed the bug where it retained the old settings

**Comment by TheoCGaming** [comment]
***hopefully*** (crossing my fingers) it'll work this time

**Comment by TheoCGaming** [comment]
it must've pulled residual data from the previous instance that was left in RAM...

**Comment by TheoCGaming** [comment]
![image](https://user-images.githubusercontent.com/65421262/180599472-20f72ef9-3987-4d5a-aab5-45665a4c189c.png)
xorg moment

**Comment by TheoCGaming** [comment]
IT WOORRRRKKKSSS

**Comment by TheoCGaming** [comment]
it was a bug with the AUR version!

**Comment by TheoCGaming** [comment]
![image](https://user-images.githubusercontent.com/65421262/180599587-012a3644-cdcc-4efd-aef5-9d21ab94811b.png)
still a bit weird though...

**Comment by TheoCGaming** [comment]
!!!
it's already installing one of my games

**Comment by TheoCGaming** [comment]
now- I wonder if what Lutris said about Fortnite is still true, that the anticheat's gonna be pissed at me as soon as I join.

**Comment by mirkobrombin** [comment]
> ![image](https://user-images.githubusercontent.com/65421262/180599472-20f72ef9-3987-4d5a-aab5-45665a4c189c.png)
> xorg moment

What

**Comment by TheoCGaming** [comment]
sometimes programs like to use parts of the screen buffer that weren't cleared properly but are now marked as unused

**Comment by TheoCGaming** [comment]
also- *is this an error that epic games **itself** is giving?!* the launcher works but not fortnite
![image](https://user-images.githubusercontent.com/65421262/180620678-4dc2d348-a513-46c7-8b7e-81aaa5025eae.png)

**Comment by TheoCGaming** [comment]
it could also just be EAC, i'll try Proton since I know that works with 7 days to die

**Comment by TheoCGaming** [comment]
and 7d2d also uses EAC

**Comment by axtloss** [comment]
Games have to enable EAC on linux support manually, it's not enabled by default. A fortnite dev has publicly said that he doesn't trust EAC on linux enough and will never support fortnite on linux. So you probably well never get it running properly.

**Comment by TheoCGaming** [comment]
> Games have to enable EAC on linux support manually, it's not enabled by default. A fortnite dev has publicly said that he doesn't trust EAC on linux enough and will never support fortnite on linux. So you probably well never get it running properly.

that makes sense

**Comment by TheoCGaming** [comment]
well i'm still trying to get QEMU working, but it's been a bit of a pain in the ass

**Comment by TheoCGaming** [comment]
.....and now for some reason EGS straight-up won't start

**Comment by TheoCGaming** [comment]
```
01:08:43: Starting BattlEye Service...
01:08:45: Failed to initialize BattlEye Service: Driver Load Error (6).
```
you're TEASING me, epic!

**Comment by TheoCGaming** [comment]
but- wait... why is Fortnite suddenly using Battleye? an entirely different anticheat...?

**Comment by TheoCGaming** [comment]
> but- wait... why is Fortnite suddenly using Battleye? an entirely different anticheat...?

@axtloss any insight?

**Comment by axtloss** [comment]
I believe Fortnite uses both battleye and easy anti cheat

**Comment by TheoCGaming** [comment]
I see

**Comment by TheoCGaming** [comment]
I'll try a fix I saw online, changing version to Win7 and re-installing BEAC.

**Comment by TheoCGaming** [comment]
I admit defeat, I am unable to run fortnite
