### ISSUE TITLE
Checksum for Fusion 360 is wrong

### ISSUE THREAD

**Issue by vadhack** [bottlesdevs/programs#110]
This show in terminal after bottles download the .exe:

14:50:50 (ERROR) Downloaded file [Fusion 360 Admin Install.exe] looks corrupted. 
14:50:50 (ERROR) Source cksum: [cf2713e186448328f0add0371135f053] downloaded: [b26e51b98bd250375d3c9a57745cb812] 
14:50:50 (ERROR) Removing corrupted file [Fusion 360 Admin Install.exe]. 
14:50:50 (ERROR) Failed to download Fusion 360 Admin Install.exe, or checksum failed. 

Please can someone help me? Thanks!

**Comment by mirkobrombin** [comment]
Fixed by 664109cbbee30e810801eb35bca1ff896ab39934. Wait some minutes for repo update.

**Comment by vadhack** [comment]
Thank you!
