### ISSUE TITLE
Can`t launch Battle launcher

### ISSUE THREAD

**Issue by ilemanovich** [bottlesdevs/programs#111]
Can`t even launch Battle launcher
What logs should I provide to help eliminate an issue?

**Comment by mirkobrombin** [comment]
I'm able to use it.
Launch bottles from terminal `flatpak run com.usebottles.bottles` then try launch and post the output here

**Comment by ilemanovich** [comment]
21:56:06 (INFO) Bottles Started! 
21:56:09 (INFO) Catalog components loaded 
21:56:09 (INFO) Catalog installers loaded 
21:56:09 (INFO) Catalog dependencies loaded 
21:56:09 (INFO) Performing Bottles checks… 
21:56:09 (INFO) Dxvks found:
         - dxvk-1.10.2
 
21:56:09 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
 
21:56:09 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
21:56:09 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
/bin/sh: строка 1: /app/bin/wine: Нет такого файла или каталога
21:56:09 (INFO) Runners found:
         - sys-
         - soda-7.0-2
         - caffe-7.10
 
21:56:10 (INFO) Setting Key External_Programs={'596f3c84-39df-4e61-a561-59b4c6fc49b9': {'executable': 'Battle.net-Setup.exe', 'name': 'Battle.net-Setup', 'path': '/run/user/1000/doc/fb1f214c/Battle.net-Setup.exe', 'id': '596f3c84-39df-4e61-a561-59b4c6fc49b9'}, 'a815eb59-b762-4dc9-b9cb-18f98e1b51cd': {'arguments': 'WINEDLLOVERRIDES="locationapi=d" %command%', 'executable': 'Battle.net.exe', 'id': 'a815eb59-b762-4dc9-b9cb-18f98e1b51cd', 'name': 'Battle.net', 'path': 'C:\\Program Files (x86)\\Battle.net\\Battle.net.exe'}} for bottle Games… 
21:56:10 (INFO) Bottles found:
         - Games
 
21:56:10 (INFO) Library saved 
21:56:14 (INFO) Launching an executable… 
21:56:14 (WARNING) Windows path detected. Avoiding validation. 
21:56:14 (INFO) Using Wine Starter -- run 
21:56:14 (INFO) Using EasyAntiCheat runtime 
21:56:14 (INFO) Using BattlEye runtime 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).

**Comment by ilemanovich** [comment]
I have reinstalled a program with deleting configs and seems like battlenet works now
Stay tuned

**Comment by ilemanovich** [comment]
Works well, thank you for fast response
