### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by StephenRynas** [bottlesdevs/programs#116]
**Title**
DirectPlay Does Not Work With "[Wargame Design Studio Games](https://wargameds.com/)"

**Which dependency?**
Microsoft DirectPlay

**Problem type**
Error establishing system as host

**Describe the problem**
This was originally submitted on March 2, 2022 as request bottlesdevs/dependencies#54 but was closed as being a duplicate to request bottlesdevs/dependencies#53. Request bottlesdevs/dependencies#53  was solved, but it did not resolve my issue concerning DirectPlay. I waited to see if updates to Bottles would solve the problem. I am now running Bottles version 2022.7.28-brescia-2 and the problem still persists. As an experiment, I was finally able to connect two Windows computers as a test. DirectPlay worked for the Windows computers.

Also see my June 12th post "[DirectPlay, What Next?](https://forum.usebottles.com/t/directplay-what-next/392)" in the Bottles forum.
 
![ScrrenShot](https://user-images.githubusercontent.com/99763298/184515271-881efff2-ece5-42cb-bc0b-34030d3f8d06.png)

**Comment by mirkobrombin** [comment]
Add a title
