### ISSUE TITLE
Leage of legends runner

### ISSUE THREAD

**Issue by gloopsies** [bottlesdevs/programs#119]
As I posted on a closed Issue about this, League of legends should be playable inside flatpak now thanks to Glorious Eggroll. It would be cool if we could try it out now

Link to the original comment: https://github.com/bottlesdevs/programs/issues/60#issuecomment-1198563201

**Comment by mirkobrombin** [comment]
Not it's still broken.
https://github.com/bottlesdevs/Bottles/issues/868
https://github.com/flathub/net.lutris.Lutris/issues/85
