### ISSUE TITLE
[Feature Request] Add more programs

### ISSUE THREAD

**Issue by blaplafla13th** [bottlesdevs/programs#13]
Can you add more program for 1 click install like Microsoft Office, 7zip, or more like in winetricks?

**Comment by mirkobrombin** [comment]
You can do it yourself  https://github.com/bottlesdevs/programs/blob/main/GUIDELINES.md

**Comment by mirkobrombin** [comment]
It's a community project. If one program is missing you can just contribute providing the installer:
https://github.com/bottlesdevs/programs/blob/main/GUIDELINES.md

If you are not able to make an installer, please fill an issue for each program is missing, providing more details as possible.
