### ISSUE TITLE
Microsoft Office installer freeze at ~50% completion

### ISSUE THREAD

**Issue by prog-amateur2** [bottlesdevs/programs#136]
Hello, I have issued a [topic](https://forum.usebottles.com/t/microsoft-office-2016-offline-version/349/9) in the forum but no news since, so I issue in this repo, thank you. 

#### Bottles version (for information) : 
`Flathub version 2022.8.28-brescia on Debian Bookworm system`

### Test with Microsoft Office 2016 installer : 
I have an **official** offline version of MS Office 2016 at home (carton box with the product key). 

The file format is a .img containing the following tree structure:
![](https://forum.usebottles.com/uploads/default/original/1X/64a07d588f916b61dac0a675f52e09375ce34da2.png)

Running the `Setup.exe` file from Bottles always freezes at ~50% completion. 

### Test with Microsoft Office Deployment Tool (ODT) installer : 
I have followed this tutorial to make `.bat` files and execute them from the Explorer browser, but the issue is exactly the same. 
This happen with x86 and x64 versions.  

I search on web since many months without success, and others have the same issue (please see the forum) : how can I make it work please ? Thank you very much for your kind help.

**Comment by mirkobrombin** [comment]
Merging with #31
