### ISSUE TITLE
COMO FAÇO PARA BAIXAR O ORIGIN ATRAVÉS DO BOTTLES?

### ISSUE THREAD

**Issue by mareagadu** [bottlesdevs/programs#14]

**Comment by mirkobrombin** [comment]
English please.

**Comment by mareagadu** [comment]
> How do I download Origin or Windows from Bottles?

**Comment by mirkobrombin** [comment]
> > How do I download Origin or Windows from Bottles?

Origin: enable the Installers feature from the experiments section in Bottles' Preferences
Windows: I'm a bit confuse 👀
