### ISSUE TITLE
Fusion 360 sign window in borked

### ISSUE THREAD

**Issue by Aasikki** [bottlesdevs/programs#142]
I was looking to do a quick 3d model for printing but unfortunately ended up a bit disappointed as the program had logged me out since last use and now the sign in page doesn't work at all.  
![image](https://user-images.githubusercontent.com/58399890/193455749-00baaa28-3c7d-44a3-82fe-a213cc92753d.png)
It's impossible to write in the email field, nothing appears if I type something and if I try to type in blindly and click next, it complains that I need to enter an email.

**Comment by mirkobrombin** [comment]
is the riched20 dependency installed?

**Comment by Aasikki** [comment]
It wasn't installed but installing it didn't do anything for me.

**Comment by Aasikki** [comment]
> is the riched20 dependency installed?

It wasn't installed but installing it didn't do anything for me.

**Comment by kenske** [comment]
Same thing happening to me. I'm trying out Bottles for the first time. I'm not able to type anything into the email field. I installed `riched20` but it made no difference.

**Comment by kenske** [comment]
Update: I installed the `allfonts` dependency and it worked!
