### ISSUE TITLE
Unable to install VPN client

### ISSUE THREAD

**Issue by mukeshgurpude** [bottlesdevs/programs#151]
I am trying to install [SonicWall Global VPN Client](https://www.sonicwall.com/products/remote-access/vpn-clients/#GVCId). It generates the following error during installation.
![image](https://user-images.githubusercontent.com/55982424/197108980-35fb1c30-8929-42e5-9157-af0f3f9ce384.png)

There are many popups after the install dialogue has been closed due to an error, which I believe indicates that some environment dependencies are missing.
![image](https://user-images.githubusercontent.com/55982424/197109326-a4c7ce88-8c66-43f2-8bd9-ad9d7c9b0a13.png)
![image](https://user-images.githubusercontent.com/55982424/197109348-60505226-e2b4-46ec-8585-afdfc090d11f.png)

I've came across [a thread from 2007](https://www.winehq.org/pipermail/wine-users/2007-May/027186.html), which says Sonicwall GVC is not working, but the thread has no replies :(

Please advise me on how to install dependencies or if I'm doing something incorrectly.

**Comment by fries1234** [comment]
Oh yeah I don't think a VPN client will work through Wine. You know if you can get a linux client of this or openvpn or wireguard files to your VPN network?

**Comment by mukeshgurpude** [comment]
Sadly, because my college uses this VPN, I am unable to change 😢. SonicWall doesn't have Global VPN Client for Linux. I'm currently using it in the VM.

Because [SoftEther VPN](https://appdb.winehq.org/objectManager.php?sClass=version&iId=37704) appears to function under wine, I thought that this one might as well 😕.
