### ISSUE TITLE
Unable to play Little Witch Nobeta in-game videos

### ISSUE THREAD

**Issue by ghost573** [bottlesdevs/programs#162]
[Little Witch Nobeta](https://store.steampowered.com/app/1049890/Little_Witch_Nobeta/) runs perfectly however has issues with the in-game cutscene that play a video file.

Previously I tried with wine-ge v7.33 where the game would crash.
Switched to caffe v7.20 and I get a white screen but the game doesn't crash.

The videos are ordinary .mp4 files that can be played normally in VLC however has no subtitles that would be displayed when played in the game.

**Comment by mirkobrombin** [comment]
Did you try Soda?

**Comment by ghost573** [comment]
Just tried with soda and vanilla wine and got a white screen just like caffe.

**Comment by mirkobrombin** [comment]
It's listed as gold in proton db https://www.protondb.com/app/1049890 so use Soda which is proton based. Take a look at the reviews or try using Steam

**Comment by ghost573** [comment]
That rating is deceptive because not all games are tested 100% to make sure all features work, this is a big issue with protondb and why I don't trust it because I tried running the game with valve's proton and here's the result I got.

![vlcsnap-2022-11-05-12h01m53s252](https://user-images.githubusercontent.com/108908286/200094302-059736bd-8346-4aa1-bf4a-a906193a2e43.png)

It's technically an "improvement" since one line of the subtitles display.

**Comment by ghost573** [comment]
Looks like it's not something Bottles can fix.
Already a report made https://github.com/ValveSoftware/Proton/issues/5486
