### ISSUE TITLE
Can't install launchers when Bottles run from 2nd SSD

### ISSUE THREAD

**Issue by berts83231** [bottlesdevs/programs#167]
System: Linux Arch (Endeavour OS)
GPU:  AMD RT 5700
Bottles: 2022.10.14.1 via Flatpak
2nd SSD mounted at /run/media/MYLINUXUSER/ssd_games

Steps to Replicate:
- Fresh install of Bottles from Flathub
- Run Bottles
- Change Bottles directory via Preferences  /run/media/MYLINUXUSER/ssd_games/bottles
- Restart Bottles
- Install required Bottles decencies automatically
- Create new Bottle called "epic"
- Try to install "Epic Installer" via Installers

Attached:
- Complete logs from Bottles installation to Epic Installer failure.
- Backup of current system config

Other Notes:
- There is no issue when I leave it as the default drive. ie my primary OS drive.
- I tried to give the Bottles Flatpak extra permissions to the ssd folder. But it did not make a difference.
- EA Installer also failed

Last message from Epic Installer before it failed
```
10:13:39 (INFO) Launching an executable… 
10:13:39 (INFO) Using Wine MSI Installer -- install 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
wineserver: file_set_error() can't map error: Function not implemented
10:13:41 (INFO) Executing installer checks 
10:13:41 (ERROR) During checks, file /run/user/1000/doc/aaca2ef6/bottles/epic/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe was not found, assuming it is not installed. Aborting. 
```
[backup_epic_configuration.yml.txt](https://github.com/bottlesdevs/programs/files/9983029/backup_epic_configuration.yml.txt)
[failed_epic_games_installation_logs.txt](https://github.com/bottlesdevs/programs/files/9983030/failed_epic_games_installation_logs.txt)

**Comment by mirkobrombin** [comment]
hit https://github.com/bottlesdevs/programs/issues/75
