### ISSUE TITLE
[Epic Games] Esync failed to open shared memory file

### ISSUE THREAD

**Issue by alvarlagerlof** [bottlesdevs/programs#17]
On system mode: 01e0:err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.

On esync mode: 01f8:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.

This may be a bottles issue in general? If so I can move it. This is in flatpak.

**Comment by mirkobrombin** [comment]
This has happened to me in the past and it is a WINE problem. I solved it by stopping all Bottles and WINE processes, then trying again. This happens when a process (in general the wineserver) is running with one type of sync but is asking to use another and fails to restart the wineserver.

**Comment by alvarlagerlof** [comment]
I see, that is weird. Your fix did remove that problem but only got me this far

```
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00f8:err:wldap32:DllMain No libldap support, expect problems
```

**Comment by mirkobrombin** [comment]
Is the bottles runtime enabled?

**Comment by alvarlagerlof** [comment]
> Is the bottles runtime enabled?

No

**Comment by alvarlagerlof** [comment]
With the latest update I get a little bit more:

```
(20:29:01) INFO Running an executable on the bottle… 
(20:29:01) INFO Using Xwayland.. 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00fc:err:wldap32:DllMain No libldap support, expect problems
0168:err:wldap32:DllMain No libldap support, expect problems
wine: Unhandled page fault on read access to 00000024 at address F7270FA0 (thread 0168), starting debugger...
01b8:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
006c:err:rpc:RpcAssoc_BindConnection syntax {57c680ac-7bce-4f39-97fd-ffea566754d5}, 0.0 not supported
```

**Comment by mirkobrombin** [comment]
```
wine: Unhandled page fault on read access to 00000024 at address F7270FA0 (thread 0168), starting debugger...
```

the one above is the blocking one but it's program-specific, I'll try to reproduce in a new clean bottle
