### ISSUE TITLE
[Battle.net] WineDbg was unable to attach

### ISSUE THREAD

**Issue by alvarlagerlof** [bottlesdevs/programs#18]
This, constantly. Probably wine.

![image](https://user-images.githubusercontent.com/14835120/146251756-e99a8978-6c79-4754-86c9-484470e0172a.png)

**Comment by mirkobrombin** [comment]
This is actually wine, idk if Bottles can do something here

**Comment by alvarlagerlof** [comment]
Maybe there is a setting to silence it?

**Comment by mirkobrombin** [comment]
> Maybe there is a setting to silence it?

Sadly not

**Comment by alvarlagerlof** [comment]
Alright then
