### ISSUE TITLE
App is buggy, official FAQ tells me to fix "internet explorer" settings. How to do that in Bottles?

### ISSUE THREAD

**Issue by BarbzYHOOL** [bottlesdevs/programs#196]
Official FAQ of the software I installed tells me "If the Simulator starts, but continues to display a blank white window even after waiting for a few seconds, then please check your settings for Internet Explorer (regardless of which browser you normally use for your web browsing). Something in the Windows settings for Internet Explorer is preventing it from displaying and running web content."

How can I edit these settings in Bottles?

**Comment by mirkobrombin** [comment]
Name of the software? A bit of context? What is your bottle configuration? What is the runner? What version of Bottles? Does it works outside of Bottles?

Please provide some information

**Comment by mirkobrombin** [comment]
Please rename the issue with the software you are trying to run.

Wine is not a full Windows implementation and some settings does not exists.

**Comment by BarbzYHOOL** [comment]
no one knows the software, and no one will help

i take this answer as a "it is not possible to do in bottles"

**Comment by mirkobrombin** [comment]
ok
