### ISSUE TITLE
I have a lot of problems!!!

### ISSUE THREAD

**Issue by Qw1zzyw** [bottlesdevs/programs#198]
When I am try to download anything from bottles it writes "Dependencies installation failed". I tried to delete and download my os but it doesn't help. Than I tried to download bottles on site but I have the same problem. I read articles about dependencies and have all of them but I can't download some new dependencies which I need. Than I found another problem I can't install anything at all. When I launch bottles I can't download any wine versions and all of another files too.

**Comment by mirkobrombin** [comment]
- [Fill a bug report](https://github.com/bottlesdevs/Bottles/issues/new) in the Bottles repository following the template
- Use a title that best explains the problem and is contextual
