### ISSUE TITLE
Installer guideline

### ISSUE THREAD

**Issue by Jan200101** [bottlesdevs/programs#2]
With the only other alternative being Lutris installers, which honestly are the result of constant monkey patching and hard to implement outside of lutris, I feel it is important to create a well designed and documented format

**Comment by mirkobrombin** [comment]
This is what we will do once the functionality is implemented in Bottles v4. It will definitely end up in the bottles documentation (docs.usebottles.com)

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/programs/blob/main/GUIDELINES.md
