### ISSUE TITLE
[Epic Games] EGS doesn't work in Bottles anymore

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/programs#21]
I'm in the Bottles Flatpak and enabled experimental Installers.

Clicked on Epic Games Store.

I got a Wine popup saying something like "wine-mono not found, we recommend your distribution's version, but we can install an internal version. Install?"

I clicked Install.

Then it said "Checksum failed. Aborting install of corrupt package" or something.

I dunno what could have caused this. Perhaps Bottles is pointing to an outdated version of dotnet installers?

**Comment by Bananaman** [comment]
I looked in the Dependencies tab, and compared it to what the Epic Games Launcher manifest wanted to install. I can see that these two are missing on my system:

- riched20
- allfonts

So I did manual installs of them from the Dependencies tab. That worked. Heh? Confusing! :)

**Comment by Bananaman** [comment]
These issues are mentioned on WineHQ actually:

https://appdb.winehq.org/objectManager.php?sClass=version&iId=35811

Scroll down to "Issues Installing vcrun2019 and dotnet4x". Seems like it could be this error.

**Comment by Bananaman** [comment]
I've installed every listed dependency manually but the Epic Launcher doesn't run.

I suspect that the manifest is incomplete:

https://github.com/bottlesdevs/programs/blob/main/Games/epicgamestore.yml

The dependencies doesn't list anything about dotnet? From what I can see, epic games is made in dotnet.

But maybe this is all related to the Wine-Mono error earlier.

**Comment by Bananaman** [comment]
I dunno...

I've manually installed every dependency from the Manifest, plus all of these that were from WineHQ:

dotnet40
dotnet48
vcredist2019
cjkfonts

Everything that I manually installed was installed without any errors.

But Epic Games still doesn't launch. Maybe it became messed up when installing due to the error message I saw. I'll try uninstalling it and reinstalling it!

**Comment by Bananaman** [comment]
Okay I began with a fresh bottle and decided to try installing Dependencies before I run the Epic Games script. This is when I noticed a problem:

On a fresh bottle, with lutris-ge runner (not tried others), trying to install "dotnet35" gives the Wine-Mono error and checksum error. Could this be related to the problem with the Epic Games Store script?

**Comment by Bananaman** [comment]
Well, darn. I just tried a brand new bottle and tried to install "dotnet40" instead. Same error. What's going on... I think this is a general Winetricks problem, not related to Bottles.

**Comment by mirkobrombin** [comment]
We do not use winetricks, Botrles came with its built in dependencies system. Can you post a screenshot of that warning about mono?

**Comment by Bananaman** [comment]
@mirkobrombin Yeah I can post a screenshot in a moment. I may have figured out the issue... It seems like I need to install wine-mono before I can install dotnet. And I see that you added wine-mono 2 days ago:

https://github.com/bottlesdevs/dependencies/blob/main/Essentials/mono.yml

I tried a totally fresh bottle and tried installing just mono, nothing else. Got that error immediately.

I then figured out something interesting...

If I click the Uninstall button on "mono", and get the add/remove dialog, and uninstall it. And then restart Bottles. And *then* try installing "mono" again, now it installs without error. Interesting...

**Comment by Bananaman** [comment]
Alright I managed to figure out more about the errors.

Steps to succeed:

1. Use latest Flatpak version.
2. Create Gaming bottle.
3. Use default settings (vaniglia runner).
4. Go immediately into the bottle and its Dependencies tab.
5. Click install on "mono". This works.

Steps to fail:

1. Use latest Flatpak version.
2. Create Gaming bottle.
3. Modify its preferences to use this runner: "lutris-ge-7.0rc2-1"
4. Go to its Dependencies tab.
5. Click install on "mono". This fails.

Error messages that pop up during install:

![Screenshot from 2021-12-22 00-33-34](https://user-images.githubusercontent.com/38923130/147011081-fd09ea8e-aca3-4944-9cd6-87c54c004cb1.png)

![Screenshot from 2021-12-22 00-33-45](https://user-images.githubusercontent.com/38923130/147011087-fc3ec866-365c-4b25-b011-cdb473260ba9.png)

**Comment by Bananaman** [comment]
@mirkobrombin My theory: Vaniglia has Wine-Mono built-in. Proton-GE doesn't. And somehow, installers are super confused by the lack of wine-mono, so that even the wine-mono installer itself fails. I dunno, just a theory.

**Comment by mirkobrombin** [comment]
Vaniglia our supported runner, also all our installers are tested on it. Try with vaniglia in a clean new bottle using our experimental installer for egs

**Comment by Bananaman** [comment]
@mirkobrombin Hmm yeah, the EGS installer script runs without errors when using vaniglia in a clean new bottle with Gaming preset.

So there's something wrong with Lutris-GE's Mono (.NET) support.

However, after EGS install, trying to run EGS gives no window at all with this clean Vaniglia gaming bottle.

Do you think it could be missing some dependencies?

Task list looks like this when I try running EGS in a clean Gaming bottle with zero settings changes:

![Screenshot from 2021-12-22 00-45-46](https://user-images.githubusercontent.com/38923130/147011806-09c78781-13f4-4548-a391-9c721d5e14bd.png)

**Comment by Bananaman** [comment]
Fresh gaming preset bottle, with only runner changed. Trying to install Dependencies: `mono`. These are my collected results:

Works:

- `vaniglia-6.23`
- `Proton-6.21-GE-2`
- `Proton-7.0rc2-GE-1` (automatic runner installer in Bottles doesn't download anything, so I extracted it manually from https://github.com/GloriousEggroll/proton-ge-custom/releases to runners directory)

Fails (with error screenshots above):

- `lutris-ge-6.21-1`
- `lutris-ge-7.0rc2-1`

I also tried installing EGS from installer script with `Proton-7.0rc2-GE-1` and it ran the script without errors. But still doesn't display any GUI when I try running EGS afterwards. I'm stuck but at least have narrowed down the `wine-mono` error to `lutris-ge`! :)

**Comment by Bananaman** [comment]
I don't think Epic Games works anymore.

I made a brand new bottle, manually installed 100% of everything (except the broken installers) on the Dependencies tab.

I then manually installed Epic Games via the .msi file via "Run Executable".

The installer ran fine and I got start menu shortcuts that became visible under "Programs". It DOESN'T use the `-opengl -SkipBuildPatchPrereq` arguments that the installer script uses. In fact, if I add that to the launch parameters, I get the "NO GUI" symptom again.

I started the pure link (no arguments) from Programs afterwards, and actually got a GUI, which downloaded some 500 MB Epic Games Launcher update.

After the download was complete, the GUI displays "Self Update Failed" and that the necessary prerequisites have failed to install:

![Screenshot from 2021-12-22 02-32-42](https://user-images.githubusercontent.com/38923130/147019789-0058f6f0-6775-4267-b67c-150eeb8e46de.png)

My conclusion:

- `-opengl -SkipBuildPatchPrereq` launch args are some kind of mistake. They make the GUI disappear.
- The application doesn't work under Wine anymore. The inability to install updates on NATIVE WINDOWS seems related to EGS needing to run with admin privileges. But I have no idea what would cause that error under Wine.

**Comment by Bananaman** [comment]
Adding just the `-SkipBuildPatchPrereq` allows the self-update to complete successfully.

But EGS itself fails to execute after that point.

It seems like `-SkipBuildPatchPrereq` means "Don't attempt to install Visual C++ runtime and other similar game requirements":

https://www.epicgames.com/help/en-US/epic-games-store-c73/error-codes-c100/ls0019-prerequisites-installation-failed-a7649

Anyway, this is totally borked. I hope my research was useful in some way, but I am stuck for today and tomorrow I'll check if the native Bottles lacks this issue, or if Lutris can install EGS (but I love the idea/design of Bottles so hoping I can make Bottles work).

**Comment by Bananaman** [comment]
I had one last idea. Made a brand new, fresh, unmodified Gaming bottle, ran the epicgamesstore script. After the install, I manually removed the `-opengl` part of the line.

Then I ran it.

The GUI appeared and began visually downloading the update:

![Screenshot from 2021-12-22 02-57-17](https://user-images.githubusercontent.com/38923130/147022033-cb2d0a53-21e8-43c8-9369-c2881421b5c1.png)

After that, it said that it successfully installed the update. The window disappeared. And nothing was running in Bottles Task Manager.

Trying to run the Programs shortcut again doesn't open any window.

Yeah, final conclusion: Epic Games Store itself is broken on Linux. There's no way that this is working for anyone else either. :P I am using the Flatpak with the same dependencies as everyone else, and the same recipe.

At the very least we need to remove `-opengl` from the arguments. But that just makes the GUI work. It's still broken and refuses to launch after that.

**Comment by Bananaman** [comment]
Just to not leave you "hanging" for answers, I uninstalled Bottles flatpak and installed native Fedora RPM: Bottles `2021.11.28-treviso`.

This is the link to the tar file they're building it from: https://src.fedoraproject.org/rpms/bottles/blob/f35/f/bottles.spec

Seems like it may be treviso-1 instead of treviso-4, dunno.

Anyway, results:

- Native.
- With default program shortcuts, I get no GUI at all.
- If I remove `-opengl` I get a GUI and it downloads the initial update. But afterwards, the GUI vanishes and the tasks vanisk too (in Task Manager).
- Trying to start it again doesn't bring up any GUI either. There are some temporary EGS related tasks but they vanish after a few seconds.

I even went with a Wine Terminal (from Bottles GUI), and went to:

- `cd "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32"`

And ran:

- `EpicGamesLauncher.exe -SkipBuildPatchPrereq`

Still no GUI.

I got the following debug output from EGS in the terminal:

```
013c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
013c:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
013c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
013c:err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UISettings"
02ac:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
02ac:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
02ac:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
03a0:err:module:import_dll Loading library D3DCOMPILER_43.dll (which is needed by L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Engine\\Binaries\\Win64\\CrashReportClient.exe") failed (error c000007b).
03a0:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Engine\\Binaries\\Win64\\CrashReportClient.exe" failed, status c0000135
wine: Unhandled page fault on write access to 0000000000000008 at address 00000001700845CE (thread 013c), starting debugger...
03ac:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
03ac:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
03ac:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```

And then after a while I got a Winedbg dialog saying that EGS had a "serious problem", with this info (I saved the backtrace):

[backtrace.txt](https://github.com/bottlesdevs/programs/files/7759488/backtrace.txt)

It looks like a null pointer write.

Eh, so yeah tomorrow I try Lutris just in case but I suspect that EGS is broken on Linux no matter what solution is used. I may end up using the Heroic/Legendary native Linux launcher instead, with Proton runtime in there...

**Comment by Bananaman** [comment]
Well, I've spent like 5 hours on this today, so why not a quick check of Lutris to give you a full report...

- Installed native Lutris RPM on Fedora 35.
- Went to "Sources: Lutris: Community Installers" and found "Epic Games Store" script and ran it.
- After installation, I went to "Games". It was there. I hit "Play".
- Epic GUI is visible. And it's doing its update.
- After the update, the window vanishes and I thought "ok so it fails too".
- A few seconds later, the Epic Games login GUI appeared.

This lets me conclude that the script that Lutris provides does the right thing. Something is missing in the Bottles installer script. Not sure what. :)

**Comment by mirkobrombin** [comment]
1. In Bottles `corefonts` is `allfonts`
2. Installers in Bottles are experimental so expect bugs
3. dxvk env vars are managed by Bottles
4. I tried on my own with a clean bottle and both vaniglia 7 RC2 unstable, vaniglia 6 latest stable and it works without the need to alter launch options or anything

![Screenshot from 2021-12-22 08-41-50](https://user-images.githubusercontent.com/9479903/147054433-10e33ced-f42e-4330-bc26-c57d4b35d93d.png)
![Screenshot from 2021-12-22 08-41-44](https://user-images.githubusercontent.com/9479903/147054434-e2812093-c5d3-4ff3-a5de-f697a9c203a1.png)
![Screenshot from 2021-12-22 08-40-16](https://user-images.githubusercontent.com/9479903/147054437-35f4eaef-cd2c-4e7f-abb7-2500b3c9d7c3.png)
![Screenshot from 2021-12-22 08-40-00](https://user-images.githubusercontent.com/9479903/147054440-6b0837c2-10e8-44a9-b828-0a4db49e936b.png)
![Screenshot from 2021-12-22 08-39-57](https://user-images.githubusercontent.com/9479903/147054443-60f42a8f-9bea-4984-9dbb-3b8e06adaec3.png)
![Screenshot from 2021-12-22 08-39-51](https://user-images.githubusercontent.com/9479903/147054446-31a26aa3-ae77-4904-8dd5-bea1c42210d3.png)
![Screenshot from 2021-12-22 08-36-10](https://user-images.githubusercontent.com/9479903/147054450-4e9ded62-da25-4710-83c8-ff756dc4e379.png)
![Screenshot from 2021-12-22 08-36-05](https://user-images.githubusercontent.com/9479903/147054452-fd765157-2d68-4486-b977-b45afe068a04.png)

**Comment by Bananaman** [comment]
@mirkobrombin Thanks for sharing your exact process! This will simplify my debugging, now I won't have to keep trying to install Dependencies manually.

I wish it had been that easy for me too. :D

I may have to install your distro and your exact version of Bottles, as a test, so what distro and Bottles versions are you using?

**Comment by mirkobrombin** [comment]
Bottles "native" fedora package is not officially supported

**Comment by Bananaman** [comment]
Yep and I don't want to use the native. I just tried it in case the Flatpak was the problem. But both of them have this problem. Since Lutris works, I have ruled out OpenGL / Wine on my system, and will keep testing to see what's wrong in Bottles Flatpak. :)

**Comment by mirkobrombin** [comment]
Does Bottles print some logs?

**Comment by Bananaman** [comment]
Hmm. I created a plain Gaming bottle with no changes, then restarted Bottles.

This is the startup log and the log of using the EGS installer script:

[1-install_egs.txt](https://github.com/bottlesdevs/programs/files/7762901/1-install_egs.txt)

Then I pressed the "play" icon on the Programs launcher for EGS, and this is all I see:

```
(14:37:12) INFO Running an executable on the bottle… 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
```

There's no GUI visible. And Bottles Task Manager lists this:

![Screenshot from 2021-12-22 14-38-47](https://user-images.githubusercontent.com/38923130/147101395-1f3533fb-c3cd-4fa4-8048-cbf86722d7c6.png)

**Comment by Bananaman** [comment]
Here is the exact bottle.yml at this moment in time:

```yml
Arch: win64
Creation_Date: '2021-12-22 14:32:23.156296'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.2
Environment: Gaming
External_Programs: {}
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- riched20
- allfonts
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.1
Name: Games
Parameters:
    aco_compiler: false
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: false
    environment_variables: ''
    esync: true
    fixme_logs: false
    fsr: false
    fsr_level: 5
    gamemode: false
    pulseaudio_latency: true
    sync: esync
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: false
Path: Games
Programs:
    EpicGamesLauncher.exe: -opengl -SkipBuildPatchPrereq
Runner: vaniglia-6.23
State: 0
Uninstallers:
    allfonts: false
    arial32: false
    courie32: false
    d3dcompiler_43: false
    d3dcompiler_47: false
    d3dx9: false
    msls31: false
    riched20: false
    times32: false
Update_Date: '2021-12-22 14:35:12.301935'
VKD3D: vkd3d-v2.4
Versioning: false
Windows: win10
WorkingDir: ''
```

**Comment by Bananaman** [comment]
I'll record the whole process and upload on YouTube :)

**Comment by Bananaman** [comment]
@mirkobrombin Alright it took me time to setup OBS and learn it. Here we go! :)

This is the whole process, it even shows my exact installed Flatpak and NVIDIA driver versions and all log messages that Bottles outputs.

https://www.youtube.com/watch?v=oQcLjlF-ROI

**Comment by Bananaman** [comment]
Oh yeah and here is the full log from the video's terminal but as text file instead:

[full_log.txt](https://github.com/bottlesdevs/programs/files/7763261/full_log.txt)

**Comment by mirkobrombin** [comment]
This will likely take some time to debug the problem. These are problems that I expect from an experimental feature and that is why we have not published it yet but it is also strange that it works on my Fedora installation (also on vm) but not on yours.

The only difference that comes to mind is that GLs are not installed via flatpak but it seems strange to me. I don't remember if you've already written it and it's hard for me to reread the whole conversation from your phone, can you try giving a flatpak update and see if you install the missing GL? In the case of NVIDIA once the proprietary drivers are installed, just do a flatpak update to install the GLs.

**Comment by Bananaman** [comment]
@mirkobrombin Yeah I thought about OpenGL issues too since it won't run with `-opengl`. I think that could be the reason. But strangely enough my flatpak list and flatpak update already shows "GL" and "nothing to do (update)". :S

I also tried native Bottles just to bypass the sandboxing to see if it could find the system OpenGL and stuff like that, but native didn't work either. It's super weird.

Whatever the cause is, it's happening in native and flatpak versions of Bottles. No issues in Lutris (which runs lutris-ge 6.something, and uses EGS `-opengl` startup switch successfully).

My system is Fedora 35, with latest NVIDIA driver (495), installed a few weeks ago and I haven't modified the system.

This is a tough one. :/

![Screenshot from 2021-12-22 16-52-50](https://user-images.githubusercontent.com/38923130/147119661-50b78d81-b51f-43d3-8070-ee02f2d9e1c6.png)

**Comment by Bananaman** [comment]
Could you please show your `flatpak list` and also exact NVIDIA driver and Fedora version?

It might be a NVIDIA 495 driver issue?

**Comment by Bananaman** [comment]
@mirkobrombin Oh god, I freaking solved it.

- Login as `GNOME` (X11) = Fails.
- Login as `GNOME on Wayland` (Wayland) = Success.

So here's the summary:

- Bottles is broken on X11.
- Lutris works on X11.
- Bottles works on Wayland.
- Lutris not tested on Wayland (already uninstalled Lutris).

**Comment by mirkobrombin** [comment]
I only use Xorg 😅 also my tests are all on Xorg only. Happy to see that it is working now but I think the problem is related to something in your xorg installation. Please can you open a specific issue in the Bottles repository to move the conversa here?

**Comment by Bananaman** [comment]
Yeah I have a bunch of ideas for X11 tests. Like checking `lsmod | grep -i nvidia` to ensure all Nvidia is loaded (please post your own result of that, I need it for debug).

Also need your Nvidia driver version for my own tests.

I will take a break with the family then make a ticket on the main Bottles project late today. :)

**Comment by mirkobrombin** [comment]
```bash
❯ lsmod | grep -i nvidia
nvidia_drm             73728  2
nvidia_modeset       1150976  3 nvidia_drm
nvidia              36950016  98 nvidia_modeset
i2c_nvidia_gpu         16384  0
drm_kms_helper        311296  2 amdgpu,nvidia_drm
drm                   630784  21 gpu_sched,drm_kms_helper,nvidia,amdgpu,drm_ttm_helper,nvidia_drm,ttm


❯ flatpak list | grep nvidia                               
nvidia-495-44	org.freedesktop.Platform.GL.nvidia-495-44		1.4	flathub	system
nvidia-495-44	org.freedesktop.Platform.GL32.nvidia-495-44		1.4	flathub	system


❯ bash <(curl -s https://raw.githubusercontent.com/bottlesdevs/tools/main/CompatibilityChecks/check-gpu-drivers.sh)
AMD graphics driver detected
NVIDIA graphics driver detected
Found a PRIME configuration.


❯ bash <(curl -s https://raw.githubusercontent.com/bottlesdevs/tools/main/CompatibilityChecks/check-session.sh)
You are running a x11 session
```

**Comment by Bananaman** [comment]
@mirkobrombin Thank you, that's very useful. I don't have `i2c_nvidia_gpu` and I have `nvidia_uvm`. And I see that my nvidia drivers run with different arguments than yours. I will try my best to figure this out.

One idea I have now is to try to run windows OpenGL test-programs in various wine Bottles.

Here are my results of all of that:

```
 ~  lsmod | grep -i nvidia
nvidia_drm             73728  10
nvidia_modeset       1150976  16 nvidia_drm
nvidia_uvm           1171456  0
nvidia              36950016  770 nvidia_uvm,nvidia_modeset
drm_kms_helper        311296  1 nvidia_drm
drm                   630784  14 drm_kms_helper,nvidia,nvidia_drm

 ~  flatpak list | grep nvidia
nvidia-495-44	org.freedesktop.Platform.GL.nvidia-495-44		1.4	system
nvidia-495-44	org.freedesktop.Platform.GL32.nvidia-495-44		1.4	system

 ~  bash <(curl -s https://raw.githubusercontent.com/bottlesdevs/tools/main/CompatibilityChecks/check-gpu-drivers.sh)
AMD graphics driver detected
Intel graphics driver detected
NVIDIA graphics driver detected
Found a PRIME configuration. <https://wiki.archlinux.org/title/PRIME>

 ~  bash <(curl -s https://raw.githubusercontent.com/bottlesdevs/tools/main/CompatibilityChecks/check-session.sh)
You are running a x11 session
```

I'll create the new ticket now on the Bottles project.

**Comment by mirkobrombin** [comment]
How do you install Nvidia prop. drivers in Fedora? Did you use the rpm-fusion repo or nvidia installer?

**Comment by Bananaman** [comment]
@mirkobrombin I created the new ticket. Should we talk here or in the new one? I linked to this from the new one. We can close this (since the proper repo links to this ticket), and continue the "messy" discussion here, perhaps.

I installed the driver via RPM Fusion:

```
dnf if xorg-x11-drv-nvidia
Last metadata expiration check: 4:38:38 ago on Wed 22 Dec 2021 14:49:41 CET.
Installed Packages
Name         : xorg-x11-drv-nvidia
Epoch        : 3
Version      : 495.44
Release      : 4.fc35
Architecture : x86_64
Size         : 56 M
Source       : xorg-x11-drv-nvidia-495.44-4.fc35.src.rpm
Repository   : @System
From repo    : rpmfusion-nonfree-nvidia-driver
```

**Comment by mirkobrombin** [comment]
> @mirkobrombin I created the new ticket. Should we talk here or in the new one? I linked to this from the new one. We can close this (since the proper repo links to this ticket), and continue the "messy" discussion here, perhaps.
> 
> I installed the driver via RPM Fusion:
> 
> ```
> dnf if xorg-x11-drv-nvidia
> Last metadata expiration check: 4:38:38 ago on Wed 22 Dec 2021 14:49:41 CET.
> Installed Packages
> Name         : xorg-x11-drv-nvidia
> Epoch        : 3
> Version      : 495.44
> Release      : 4.fc35
> Architecture : x86_64
> Size         : 56 M
> Source       : xorg-x11-drv-nvidia-495.44-4.fc35.src.rpm
> Repository   : @System
> From repo    : rpmfusion-nonfree-nvidia-driver
> ```

In the other one
