### ISSUE TITLE
Automatically refresh Programs after using Installer

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/programs#22]
After installing Epic Games Launcher, I went to the Programs tab. It was empty.

I clicked the Refresh icon and the launcher appeared.

For better user-experience, should trigger a refresh after any Installer script is used. :)

**Comment by mirkobrombin** [comment]
Tracking here #773

**Comment by Bananaman** [comment]
@mirkobrombin Where? ^^ That's not a link to anything.

**Comment by mirkobrombin** [comment]
Sorry https://github.com/bottlesdevs/bottles/issues/773

**Comment by Bananaman** [comment]
@mirkobrombin Thanks! :)
