### ISSUE TITLE
After installing Fusion 360 I can't login

### ISSUE THREAD

**Issue by cortopy** [bottlesdevs/programs#224]
Fusion 360 requires to log in using browser in order to start using the program. I have just installed Fusion 360 OK, but when I get to the login prompt and I click on "log in" nothing happens.

It seems as if no browser exists or can't open a browser. I've tried debugging running from terminal but no new log lines are output when pressing login

**Comment by lrdeoliveira** [comment]
I'm having the same problem

**Comment by 20000000h** [comment]
Вы нашли решение?

**Comment by 20000000h** [comment]
> I'm having the same problem

Have you found a solution?

**Comment by kd8bny** [comment]
Not a solution, but upstream has reverted the installed version.

https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v7.6.7
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/319

**Comment by jhoblitt** [comment]
I'm guessing that a browser needs to be installed into the bottle.

**Comment by sommerper** [comment]
When I try to sign in my default browser does open up to start the sign in process - but crashes my system (popos 22.04) once it wants to redirect to Fusion.

**Comment by digitamo** [comment]
> When I try to sign in my default browser does open up to start the sign in process - but crashes my system (popos 22.04) once it wants to redirect to Fusion.

Same here on ubuntu 22.04
