### ISSUE TITLE
Ubisoft Connect Crashes after Updating

### ISSUE THREAD

**Issue by Janybanny** [bottlesdevs/programs#227]
I didn't use Ubisoft Connect through bottles for a few months and wanted to launch a game again. After opening Ubisoft Connect, it decides to update itself and then restart. While restarting it shuts down and doesn't start again. After manually starting again, it launchers and stops with the error below. After pressing OK, it closes.

![Screenshot_20230419_221705](https://user-images.githubusercontent.com/62150940/233190084-6b708fed-d764-4f5c-aa2f-48685c06291a.png)

(The pink border is my window border theme, ignore that please)

This is happening with both the soda and wine-ge runners.
This is happening on the old and on a completely new bottle.

I have uploaded all the crash dumps here, I have no idea if you can do anything with them (my technical knowledge isn't good enough for that)
https://drive.proton.me/urls/MJJ2B2FGD4#VZTSyM3Z0Ju9

This might be similar to #190 , but I get an error and they don't, so I decided to open a new issue. Please merge if incorrect.

Please let me know if I can assist with anything else.

**Comment by Janybanny** [comment]
I just tested it again and it works now. Let's hope it stays that way

**Comment by poperigby** [comment]
I'm having the same issue.

**Comment by leochras** [comment]
Might consider reopening @Janybanny

**Comment by Janybanny** [comment]
Happens again after the latest Ubisoft Connect Update for me as well

**Comment by mirkobrombin** [comment]
Had the same problem some days ago, fixed by killing the process and starting again.

**Comment by Janybanny** [comment]
That seems to fix it for me as well. I don't use ubisoft connect very often, sorry for the long wait. I think there isn't much more that we can do anyways, so having this open for a more permanent fix doesn't make sense.
