### ISSUE TITLE
Can't play online in R6S.

### ISSUE THREAD

**Issue by Corbony** [bottlesdevs/programs#228]
This is my first time using bottle I installed Uplay (Ubisoft Connect) and downloaded R6S (Rainbow Six Siege) and it gets to the Main menu and I can matchmake but it always fails to connect when a match is found. Any help. Any settings I gotta change? Or is this a siege issue.
Using Steam Deck

**Comment by poperigby** [comment]
Rainbow 6 Siege uses anti-cheat, so it won't work on Linux unless they explicitly make it work.
