### ISSUE TITLE
How to test Installer?

### ISSUE THREAD

**Issue by gbtb** [bottlesdevs/programs#23]
Hello.

I'm very excited about Installer feature of Bottles, and I'd like to create installer for a program.
But how do I test Installer before pushing it into this repo?
Is there a way to point Bottles to a .yml file on my computer?

**Comment by mirkobrombin** [comment]
Hi, currently not but you can just reproduce the steps manually https://forums.usebottles.com/d/13-how-to-create-installers-example

**Comment by fosspill** [comment]
This is definitely needed down the line. Especially if #24 is completed as there may be some exotic scripts to run which could act differently within bottles

**Comment by gbtb** [comment]
I was able to monkey-patch BottlesRepositories.installers repo url to "file:///path/to/local/repo" , and it worked.

But for a normal usage I think it is better to have entry in preferences menu, either with "test repo" path to override main one, or maybe even allow user to supply multiple repositories paths.

**Comment by mirkobrombin** [comment]
What about a env var like LOCAL_INSTALLERS which set that to a specific path inside bottles? This is a little bit tricky but easy to implement.

**Comment by fosspill** [comment]
For those who just want to test installers I think it's perfectly fine. The people who will be creating installers would likely be used to having to set env vars anyways.

The only question is if you'd like for people to be able to define custom repositories for other reasons. Say I want to maintain my own repo with installers that I fully support.

Maybe that's a feature for a later date, however

**Comment by mirkobrombin** [comment]
I think we should improve the main one but can be fine when users need to share private software, like office stuff

**Comment by gbtb** [comment]
> What about a env var like LOCAL_INSTALLERS which set that to a specific path inside bottles? This is a little bit ugly but easy to implement.

I think this a good compromise, at least for a start. If later users will express demand in additional remote repos, it can be implemented then.

**Comment by mirkobrombin** [comment]
Implemented 3 env vars:
- `LOCAL_COMPONENTS` 
- `LOCAL_DEPENDENCIES`
- `LOCAL_INSTALLERS`

so we can use a local path for just one or all repositories. These should be set like this: `LOCAL_DEPENDENCIES=/var/home/mirko/Projects/bottlesdevs/dependencies` and a `index.yml` file on root is required. The best way is to just `git clone` the needed repository and make edits on it.

Bottles will look for the `index.yml` and if it does not exists, will rollback to standard repositories, to be sure all is working, look for this on start:
![image](https://user-images.githubusercontent.com/9479903/148353871-5c70eadf-dd2b-4517-ba0a-4e76e9404395.png)

**Comment by DragonflyRobotics** [comment]
It doesn't seem to work for me when I set the LOCAL_INSTALLERS variable. I cloned the programs repo, changed the index, added my manifest to the Software directory and ran the following:
```
LOCAL_INSTALLERS=/home/krishna/Documents/Bottles/programs/ flatpak run com.usebottles.bottles
```

```
14:59:09 (INFO) Bottles Started! 

(bottles:2): Gtk-WARNING **: 14:59:09.978: AdwViewSwitcher 0x562610b92b40 (viewswitcher) reported min height -6, but sizes must be >= 0
14:59:12 (ERROR) Local installers path does not exist: /home/krishna/Documents/Bottles/programs/ 
14:59:14 (INFO) Performing Bottles checks… 
14:59:14 (INFO) Dxvks found:
	- dxvk-2.3
 
14:59:14 (INFO) Vkd3ds found:
	- vkd3d-proton-2.11.1
 
14:59:14 (INFO) Nvapis found:
	- dxvk-nvapi-v0.6.4
 
14:59:14 (INFO) Latencyflexs found:
	- latencyflex-v0.1.1
 
14:59:14 (INFO) Runners found:
	- soda-8.0-2
	- sys-wine-8.0.2
 
14:59:14 (INFO) Bottles found:
	- Fusion
	- Fusion360-Custom
 
14:59:14 (INFO) Catalog dependencies loaded 
14:59:14 (INFO) Catalog installers loaded 
14:59:15 (INFO) Catalog components loaded 
```

Note the error. The path is correct and there is an index.yml inside the programs folder just as intended.
