### ISSUE TITLE
[Installers] Set enviroment variables for bottle

### ISSUE THREAD

**Issue by fosspill** [bottlesdevs/programs#25]
Is it possible to define specific environment variables that needs to be set for the installed program to run?

If not I think this would be a great addition

**Comment by mirkobrombin** [comment]
Some sort of environment variables that Bottles should injected by default?

**Comment by fosspill** [comment]
I'm not sure about that as it would be very specific for specific use cases.

Specifically I'd like for my installer to set  `XL_WINEONLINUX=true` for the bottle where it is ran.

Presumably a "set_env_var" action would be good, if nothing like it exists?

**Comment by mirkobrombin** [comment]
Oh sorry I got it. You are talking about env vars for programs installed using our installers (?)

I think this was already scheduled or at least requested by another user, btw I really want to provide such action.

**Comment by mirkobrombin** [comment]
Nvm, it is already possible to register env variables using installers, just setting the arguments like: `ENV1=val1 %command% -arg1`.
