### ISSUE TITLE
Ubisoft connetct not Starting

### ISSUE THREAD

**Issue by Pelikan-71-57-1** [bottlesdevs/programs#253]
Hello since Tuesday (my) the Ubisoftconnect is not starting any more.
See also this issue: https://github.com/bottlesdevs/Bottles/issues/2994

Package:
Flatt-pack
Distribution:
Garuda Linux (Arch Fork)
Runner:
Tried many different runners

On Sunday and Monday it was still running using  the: wine-ge-proton-8-12 as runner
the regular Runner was already broken back then.
But Tuesday  Ubisoft connect did me the favor to update and break it self

If any more Information is necessary i will help

**Comment by Gamertech** [comment]
The Ubishaft app has been fixed in Proton experimental branch (for now), just need that to filter through to soda/GE.
