### ISSUE TITLE
Battle.net won't install 

### ISSUE THREAD

**Issue by Brunvik** [bottlesdevs/programs#255]
Starting the installer via the Bottles script will end up having an error an the actual application install. 
![Bildschirmfoto vom 2023-08-02 21-13-34](https://github.com/bottlesdevs/programs/assets/141272014/b2bed711-4833-4c52-bc16-0be7de2ee8f9)

**Comment by mirkobrombin** [comment]
What's your bottle setup? A standard Gaming?

**Comment by Brunvik** [comment]
Basically everything on default when choosing gaming as Setup

**Comment by mirkobrombin** [comment]
Can you remove the bottle, clean up your templates folder and make a new one?
To clean up the templates folder, simply remove ~/.var/app/com.usebottles.bottles/data/bottles/templates/ while Bottles is closed.

**Comment by Brunvik** [comment]
Had the same struggle on a install before I redid my setup, did not archieve to ger Battle.net installed with bottles (before worked flawlessly!) , I had guessed blizzard broke something

**Comment by mirkobrombin** [comment]
There is high chance that Blizzard did something wrong.

**Comment by Brunvik** [comment]
Error code suggests that it has no connection to the patching server, maybe the used battle.net version to actually install it isn't supported anymore or something else entirely on their part.

**Comment by mirkobrombin** [comment]
Try downloading the latest bnet installer from their website

**Comment by mirkobrombin** [comment]
I'll update our installer

**Comment by Brunvik** [comment]
I personally thank you!
