### ISSUE TITLE
Low latency input via Pipewire in Ableton Live 10?

### ISSUE THREAD

**Issue by deusnovus** [bottlesdevs/programs#268]
Reporting back after having solved #236 and everything works perfectly fine.

I was just wondering though, is there a way to have low latency input via Pipewire within Bottles? The only available audio inputs / outputs I have are my audio card and PulseAudio, of which their lowest latency levels are 256ms, which is pretty high for any kind of audio/MIDI playback. Thank you.

![Screenshot from 2023-09-23 18-17-25](https://github.com/bottlesdevs/programs/assets/32219080/0bf5a531-6036-4c06-806a-e302ded45d79)

**Comment by orowith2os** [comment]
This is an upstream Wine problem; Bottles can't do anything about using PipeWire or not. You'd do better to go to official Wine channels.
