### ISSUE TITLE
[EA App] Help Needed: How to install on Bottles?

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/programs#27]
EA App (previously known as EA Desktop) is the replacement for Origin.

1. The installer file is here: https://www.ea.com/ea-app-beta
2. According to this report, it works on plain Wine: https://appdb.winehq.org/objectManager.php?sClass=version&iId=40425
3. According to this Lutris script, it works in Lutris without any special techniques needed: https://lutris.net/games/install/29855/view

Tried it on Caffe 7.0 and 6.23 without any success. The GUI version just shows a giant exclamation mark (warning symbol). The `/silent` mode doesn't install anything either.

If anyone figures it out, please post here so we can make an installer script for it.

**Comment by mirkobrombin** [comment]
Can you try it in a custom environment without any dependencies? And so provide the log if it fails please

**Comment by Bananaman** [comment]
Starting Bottles and creating custom bottle with caffe-7.0, dxvk-1.9.3, and 64-bit:

[0_start.txt](https://github.com/bottlesdevs/programs/files/7899222/0_start.txt)

Copying EAappinsaller into the bottle and trying to start it:

```
(18:26:39) INFO Running an executable on the bottle… 
(18:26:39) INFO Setting Key: [Latest_Executables] to [[{'name': 'EAappInstaller.exe', 'file': '/home/johnny/.var/app/com.usebottles.bottles/data/bottles/bottles/EA/drive_c/EAappInstaller.exe', 'args': ''}]] for bottle: [EA]… 
wineserver: using server-side synchronization.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0068:err:module:open_builtin_so_file failed to load .so lib "/home/johnny/.var/app/com.usebottles.bottles/data/bottles/runners/caffe-7.0/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0124:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0124:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```

Guess what? The GUI appeared, and I did an install. Or so I thought. I pressed "Let's Go!" and saw a progress bar. After a while, the red exclamation mark appeared.

Logs that appeared during install:

```
0284:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0284:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
02bc:err:richedit:ReadStyleSheet skipping optional destination
02bc:err:richedit:ReadStyleSheet skipping optional destination
02bc:err:richedit:ReadStyleSheet skipping optional destination
02bc:err:richedit:ReadStyleSheet skipping optional destination
025c:err:msi:MsiEnableLogW Unable to enable log L"C:\\users\\johnny\\Temp\\EA_app_20220119182640_005_EAapp.msi.log" (32)
025c:err:msi:ITERATE_Actions Execution halted, action L"JunoInitializeSession" returned 1603
```

And as for why it didn't launch at all in my existing bottle, it could be because I've enabled DXVK and NVAPI...

**Comment by mirkobrombin** [comment]
I’ll try on my own

**Comment by Bananaman** [comment]
@mirkobrombin I tried disabling DLSS/NVAPI, gamemode, discrete GPU, DXVK, VKD3D in my existing bottle but no success. Still instant exclamation mark. It's weird but I suppose it could be because of something that's been installed on the Dependencies tab or something marked as native DLL. There's no interesting log errors though. Let's see if it works on your computer. :)

**Comment by mirkobrombin** [comment]
Investigating on this:
```
01a8:err:msi:ITERATE_Actions Execution halted, action L"JunoInitializeSession" returned 1603
0190:err:ole:apartment_add_dll couldn't load in-process dll L"C:\\windows\\system32\\mshtml.dll"
0190:err:ole:create_server class {25336920-03f9-11cf-8fd0-00aa00686f13} not registered
0190:err:ole:com_get_class_object no class object {25336920-03f9-11cf-8fd0-00aa00686f13} could be created for context 0x17
0190:err:ole:apartment_add_dll couldn't load in-process dll L"C:\\windows\\system32\\mshtml.dll"
0190:err:ole:create_server class {25336920-03f9-11cf-8fd0-00aa00686f13} not registered
0190:err:ole:com_get_class_object no class object {25336920-03f9-11cf-8fd0-00aa00686f13} could be created for context 0x17
0190:err:ole:apartment_add_dll couldn't load in-process dll L"C:\\windows\\system32\\mshtml.dll"
```

The only real difference from a bottle (from Bottles) and a common wineprefix, is that we do not automatically install mono and gecko. I'll try with these installed.

**Comment by mirkobrombin** [comment]
Manifest: https://github.com/bottlesdevs/programs/blob/main/Games/eaclient.yml (should works just out of the box in 2022.1.14 but only tested with 2022.1.28)

**Comment by Bananaman** [comment]
Thank you so much for solving it! The installation manifest works perfectly! (I should have posted this earlier but apparently didn't, so I'll add it now. :))
