### ISSUE TITLE
Add Proton-GE stable Flatpak as runner

### ISSUE THREAD

**Issue by deadmeu** [bottlesdevs/programs#276]
When setting up the Proton GE runner, it seems like currently you can only select to download and install a specific version of ge-proton. It would be nice if, additionally, you could specify to use the prepackaged Flatpak (com.valvesoftware.Steam.CompatibilityTool.Proton-GE) as a runner so that it is automatically kept up-to-date.

**Comment by jntesteves** [comment]
`com.valvesoftware.Steam.CompatibilityTool.Proton-GE` is deprecated, it's unmaintained and may be removed in the future. All Flatpak packaged Proton versions have been discontinued, it's up to apps to package their own Proton.

Also, just so you know, this is not the right repository. Wine/Proton runners are maintained in https://github.com/bottlesdevs/components
