### ISSUE TITLE
Epic Games Store Installer

### ISSUE THREAD

**Issue by gat02** [bottlesdevs/programs#28]
Hi,

I'm trying out the Epic Game Store Installer. Everything installs but when I try to run Epic Game Store nothing happens. I clicked on the triple dots next to it and browse path. The Binaries folder open in file manager but the EpicGamesLauncher.exe is in the Win32 folder.

I looked at the epicgamestore.yml and the path is written for the executable.
Executable:
  name: Epic Games Store
  icon: epicgamestore.svg
  file: EpicGamesLauncher.exe
  path: Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32
  arguments: -opengl -SkipBuildPatchPrereq

I think it might need a / at the end of Win32.
path: Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/

Thanks

**Comment by mirkobrombin** [comment]
Can you share the bottle.yml?

**Comment by gat02** [comment]
[bottle.txt](https://github.com/bottlesdevs/programs/files/7966205/bottle.txt)

**Comment by mirkobrombin** [comment]
Thame path should point to the executable and not the parent folder. Can you try to append the executable name to the path and restart bottles?

**Comment by gat02** [comment]
I was just trying it out. When I put a / at the end of Win32 and check browse path it would go in the proper folder. But when I try to run Epic Launcher nothing happen.

But it works when I append the executable. I was thinking of appending but I saw the executable line so I though it might automatically run that.

Thanks.
