### ISSUE TITLE
Battle.net Installer Checksum Failure

### ISSUE THREAD

**Issue by roma0104** [bottlesdevs/programs#283]
Host OS: Devuan Daedalus/Debian 12
Flatpak: 1.14.4
Bottles: v51.9 (Flatpak)

Create a Gaming Bottle.
Install the Battle.Net program using the built-in 'recipe'.
Installation fails with message: "Dependencies installation failed."

Running bottles from the terminal the failure occurs at the download of Visual C++ redistribution x64 with a checksum mismatch. 

<pre><span style="color:#33DA7A">VC_redist.x64.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (24.1MiB/24.1MiB - 24.2MiB)</span>

15:10:43 <b>(INFO)</b> <span style="color:#2AA1B3">Renaming [VC_redist.x64.exe] to [vcredist2019_x64.exe].</span> 
15:10:43 <b>(ERROR)</b> <span style="color:#C01C28">Downloaded file [VC_redist.x64.exe] looks corrupted.</span> 
15:10:43 <b>(ERROR)</b> <span style="color:#C01C28">Source cksum: [744b8a391e7e914c6604a533b50a6db8] downloaded: [e091e9e5ede4161b45b880ccd6e140b0]</span> 
15:10:43 <b>(ERROR)</b> <span style="color:#C01C28">Removing corrupted file [VC_redist.x64.exe].</span> 
</pre> 

This is with a clean installation and I tried trashing the flatpak Bottles directory. The error is produced.

I don't think this is a bug with Bottles but the 'recipe' for Battle.net. Feel free to move or close as needed.

**Comment by roma0104** [comment]
Attempting to install the dependency by itself produces the same checksum mismatch error.

**Comment by xioren** [comment]
This was fixed with [210](https://github.com/bottlesdevs/dependencies/pull/210).

**Comment by MakkaKaplar** [comment]
Seems like the checksum has changed again:
```
19:09:12 (ERROR) Downloaded file [VC_redist.x64.exe] looks corrupted. 
19:09:12 (ERROR) Source cksum: [e091e9e5ede4161b45b880ccd6e140b0] downloaded: [35431d059197b67227cd12f841733539] 
19:09:12 (ERROR) Removing corrupted file [VC_redist.x64.exe]. 
```

**Comment by MakkaKaplar** [comment]
Made a PR for this [211](https://github.com/bottlesdevs/dependencies/pull/211)
