### ISSUE TITLE
Battle.net - Couldn't verify a digital signature

### ISSUE THREAD

**Issue by JonBoyleCoding** [bottlesdevs/programs#285]
Host: NixOS 23.11
Bottles Version: 51.9

Simply put, when installing I get this error during the launcher installation. This is a fresh bottle setup with "Gaming" during creation.  I've tried deleting everything and starting again and get the same error. This happens when trying to download updates.

I also tried manually downloading the battle.net setup and running it inside the bottle and I have the same issue

![image](https://github.com/bottlesdevs/programs/assets/630329/5758e37d-8cc3-47a4-b4a1-3ba5df1becae)

Nothing appears in the terminal that appears to be of any use. You can see that it thinks the install has completed successfully when it hasn't.

```
00:47:43 (INFO) Installing dependencies
00:47:43 (INFO) Updating bottle parameters
00:47:43 (INFO) Setting Key dxvk=True for bottle Blizzard…
00:47:43 (INFO) Setting Key discrete_gpu=True for bottle Blizzard…
00:47:43 (INFO) Executing installer steps
Battle.net-Setup-enUS.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (4.7MiB/4.7MiB - 7.5MiB)
00:47:44 (INFO) Launching an executable…
00:47:54 (INFO) Starting 2 monitors
00:47:54 (INFO) Setting Key a4a2be2b-d4f4-40d6-ad44-eb5c7008e8c0={'executable': 'Battle.net.exe', 'arguments': 'WINEDLLOVERRIDES="locationapi=d" %command%', 'name': 'Battle.net', 'path': 'C:\\Program Files (x86)\\Battle.net\\Battle.net.exe', 'id': 'a4a2be2b-d4f4-40d6-ad44-eb5c7008e8c0'} for bottle Blizzard…
00:47:54 (INFO) Program installed: battlenet in Blizzard.
```

This is my first time using bottles - so I'm not sure where to try diagnosing from here.

**Comment by mirkobrombin** [comment]
Could be a problem with Blizzard' servers. It happens. Try again in a few hours or try a different runner, like wine-ge instead of Soda.

**Comment by Baadvo** [comment]
I have the same problem. It's been going on for 3 days. I'm trying to install regularly.
Manjaro linux 23.1.0
Bottles 51.9 (flat)
