### ISSUE TITLE
FL Studio link no longer exists

### ISSUE THREAD

**Issue by Sushii64** [bottlesdevs/programs#324]
Trying to install FL Studio results in an error saying that the page is not found.
Opening the page listed in the manifest also results in a 404 error.

The current link is https://install.image-line.com/flstudio/flstudio_win64_24.1.1.4239.exe.

**Comment by The-Darumonkey** [comment]
I can replicate this - the manifest in the installer for FL Studio points to an installer that is no longer available. 

Currently, the manifest points to: https://demodownload.image-line.com/flstudio/flstudio_win64_21.2.3.4004.exe

Pasting this into the browser gives a 404: Not found error.

Changing the URL to https://demodownload.image-line.com/flstudio/flstudio_win64_24.1.1.4239.exe results in a download starting. 

If I could find the appropriate manifest file, I could probably fix this myself.

**Comment by Sushii64** [comment]
The issue with the new installer is that it runs the MS Edge installer which needs to be manually killed, but I don't know how you'd do that automatically

**Comment by The-Darumonkey** [comment]
> The issue with the new installer is that it runs the MS Edge installer which needs to be manually killed, but I don't know how you'd do that automatically

For the time being, it's enough for us to know that manually killing the process finalises the install.

For other users, it would, of course, be better to update the installer bottle.

**Comment by Sushii64** [comment]
The main issue is that you can't open Task Manager since the main Bottles window is inaccessible when using the installer feature.
Works fine when running the executable by itself, just when this window (see below) is open, you can't interact with the main window
![image](https://github.com/user-attachments/assets/8d8db35a-9228-4423-90b5-d7d6474f5244)

**Comment by NischalDawadi** [comment]
So how can i install it without error.

**Comment by TH3-F001** [comment]
is there a way users can edit or override the manifest while we wait for a fix to get pushed?

**Comment by mujehoxe** [comment]
Same here

**Comment by Torbuntu** [comment]
I have been successful in manually downloading the latest installers and running them directly in a bottle. 
https://support.image-line.com/redirect/flstudio_win_installer
