### ISSUE TITLE
EA Launcher has wrong cksum, cant install 

### ISSUE THREAD

**Issue by kleinermob** [bottlesdevs/programs#34]
Downloading EAappInstaller.exe: 100% [==================================================>

(23:11:55) ERROR Downloaded file [EAappInstaller.exe] looks corrupted. 
(23:11:55) ERROR Source cksum: [7e6eeb0fc19a9d5ce9ebeee7b4491e35] downloaded: [e4c63ac2e6075c18e16eb973823f11aa] 
(23:11:55) INFO Removing corrupted file [EAappInstaller.exe]. 
(23:11:55) INFO Setting Key: [dxvk] to [True] for bottle: [EA]… 
(23:11:55) INFO Setting Key: [discrete_gpu] to [True] for bottle: [EA]… 
(23:11:55) INFO Setting Key: [EADesktop.exe] to [{'executable': 'EADesktop.exe', 'arguments': '', 'name': 'EA Client', 'path': '/home/raja/.var/app/com.usebottles.bottles/data/bottles/bottles/EA/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EADesktop.exe'}] for bottle: [EA]… 
(23:11:55) INFO Using WINE debug tool 
(23:11:55) INFO Using WINE debug tool 
(23:11:55) INFO Using WINE debug tool 
(23:11:55) INFO Using WINE debug tool 

flatpak btw

**Comment by minuq** [comment]
```12:25:25 (ERROR) Downloaded file [EAappInstaller.exe] looks corrupted.
12:25:25 (ERROR) Source cksum: [6c430e5aa9f9bb7b48135bb88707f250] downloaded: [2603f4955acdd33318ee92d04d2c13a3]
12:25:25 (ERROR) Removing corrupted file [EAappInstaller.exe].
12:25:25 (ERROR) Failed to download EAappInstaller.exe, or checksum failed.```
Same issue as initially
