### ISSUE TITLE
Microsoft Visual C++ Runtime vs Microsoft Visual C++ Redistributable

### ISSUE THREAD

**Issue by capi1O** [bottlesdevs/programs#342]
A program I use needs Microsoft Visual C++ 2010 SPI (x64) Runtime, in wine this is called `vcrun2010` (https://appdb.winehq.org/objectManager.php?sClass=version&iId=26525).

I did install `vcredist2010` dependency in Bottles but I still have the error message so I was wondering if it was the same or something different.

**Comment by jntesteves** [comment]
I'm pretty sure they are the same thing. Microsoft named the installers vcredist. Winetricks calls them vcrun, Bottles calls them vcredist.

**Comment by capi1O** [comment]
Ok thank you very much for the answer, it's probably a silly question but I just wanted to make sure. Turns out the program I was trying to install finally worked after changing the runner from `soda` to `caffe`.
