### ISSUE TITLE
Added Rockstar Games Launcher

### ISSUE THREAD

**Issue by RaulKong898** [bottlesdevs/programs#349]
### Tell us the problem or your need

1. Manual installation of Rockstar Games Launcher is required to play GTA V, which complicates the setup process.
2. In GTA V, the mouse cursor disappears in certain menus during online play, specifically the Rockstar Account menu.

### Describe the solution you'd like

1. Adding Rockstar Games Launcher to the list of apps automatically installed by Bottle.
2. Making the mouse cursor visible in all GTA V menus regardless of game mode (online or offline).

### Other solutions?

Investigating the ability to force cursor visibility through changes to the Bottle configuration for GTA V.

### Additional context and references

The addition of the Rockstar Games Launcher to auto-install has significantly simplified the setup process for Bottle users who want to play Rockstar games, especially GTA V.

**Comment by GabsEdits** [comment]
There seems to be one: https://github.com/bottlesdevs/programs/blob/main/Reviews/rockstar.md

**Comment by HJHughJanus** [comment]
@GabsEdits Rockstar Games Launcher is known to have problems with Wine, Proton and Soda (a quick reddit or google search will show you). Please don't dismiss this.

**Comment by ikcikoR** [comment]
> Rockstar Games Launcher is known to have problems with Wine, Proton and Soda (a quick reddit or google search will show you). Please don't dismiss this.

That's for Wine/Proton/Soda to fix I think. Also GTA Online blocked Linux recently because of their new anticheat that is set to not allow it.
