### ISSUE TITLE
[BUG] GOG Galaxy installer required dotnet40 too

### ISSUE THREAD

**Issue by psydvl** [bottlesdevs/programs#35]
While trying to install GOG Galaxy on fresh bottle got a lot of error:
```
0450:err:imagehlp:BindImageEx Import "C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\" was not found.
```
And some others

That's not a problem to end installation, but can be solved with just installed dotnet40

**Comment by mirkobrombin** [comment]
I've just removed dotnet48 as a dependency (witch also install dotnet40) because cause a lot of errors. If dotnet40 is enough I can add it

**Comment by mirkobrombin** [comment]
But are these blocking?

**Comment by mirkobrombin** [comment]
I'll test again on my own, thanks
