### ISSUE TITLE
[Feedback] Possible missing dependencies in Epic Games Store installer

### ISSUE THREAD

**Issue by Rahul-R5** [bottlesdevs/programs#49]
I have tried to install the epicgames store through the installers provided and it has always gotten stuck on one or the other step and never completes. I looked at the manifest and thought of installing it manually. I ran the msi in the bottle and installed it, then installed the dependencies specified in the manifest. At this point when I try to launch the store it gave this error: `SU-PQR1603`. Checking on the epic support [page](https://www.epicgames.com/help/en-US/epic-games-store-c73/error-codes-c100/how-do-i-fix-the-epic-games-launcher-when-i-get-the-error-the-necessary-prerequisites-have-failed-to-install-a3511), it suggested to install VC Redist 2010, 2012, 2013 and 2015 which was easily available in bottles.

After installing it, surprise it just worked! There was no problems in using the store and playing games. BONUS: The installer for Epic Online Services (Installed through the store) [required](https://www.epicgames.com/help/en-US/epic-games-store-c73/error-codes-c100/eoserr1603-a9494) `.NET Framework 3.5` and installed with no problems after the dependency was met.

**Comment by Rahul-R5** [comment]
I haven't tried creating a new installation but keeping just vcredist 2015 on the current installation works well too

**Comment by felipemarkson** [comment]
I had the same issue. To solve this, I first added the vcredist2015 and vcredist2015. Then I installed Epic Store.

Version: 2022.4.28
Package: Flatpak
OS: Arch Linux
DE: Gnome

I think at least the vcredist2015 must be added as a dependency.
