### ISSUE TITLE
EA Launcher and Origin not installing

### ISSUE THREAD

**Issue by Willdrick** [bottlesdevs/programs#51]
The install fails due to dependencies, checked on terminal and I can see it downloads firefox, then renames the .exe file as a .7z but it won't unzip it 
![imagen](https://user-images.githubusercontent.com/2455158/162356343-3aa43eb5-7b8a-483b-b9b3-7864657a62f8.png)

**Comment by mirkobrombin** [comment]
Do you have p7zip installed?

**Comment by Willdrick** [comment]
yes, if you look at the screenshot, the error is not that it's not finding `7za`, it's that it fails to open the archive, which I also tried manually, and it doesn't work either.

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/162431252-60785c0e-207c-47de-a3fe-8c922796d513.png)

That's weird

**Comment by jayp76** [comment]
Same problem on Fedora 35. The installed 7za cannot ectract the file. If i manually use 7zip's port "7zz" i can ectraxt that file.

**Comment by mirkobrombin** [comment]
I think this is a dependency problem and should be reported to the maintainer
