### ISSUE TITLE
[Request]: Add installer support for Riot and  Garena League of Legends

### ISSUE THREAD

**Issue by zihaaad** [bottlesdevs/programs#60]
### Tell us the problem or your need

League of Legends runs smooth in linux. recently Glorious eggroll [released](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-2-LoL) a ge-lol build which fixes long time loading. It would be very helpful if you include Garena and Riot launcher League of Legends in Bottles. It will save us lots of time. 
visit r/leagueoflinux for more information.

### Describe the solution you'd like

One click installer for Garena League of Legends and Riot League of Legends.

**Comment by gloopsies** [comment]
According to https://twitter.com/GloriousEggroll/status/1552191083391713283?cxt=HHwWhoC80aDkvoorAAAA League should now be playable inside flatpak. Is it time to test the install script?

**Comment by UpsettingBoy** [comment]
Is not *yet\** playable in flatpak until the next version with patched `modify_ldt` releases. But an installer could be created and merged when the next version of flatpak is released/mainstreamed into various distros.

* I've been playing via patched flatpak for a while and it's great!

**Comment by zihadio** [comment]
@UpsettingBoy you talking about this [patch](https://github.com/flatpak/flatpak/commit/bd53d4096232366c27791fe523eabb6cb52fd3d5)?
I hope I will be able to install Garena or riot client through flathub.

**Comment by UpsettingBoy** [comment]
Exactly! If you wanna try, in the AUR is something called `flatpak-lol` and in [Fedora](https://copr.fedorainfracloud.org/coprs/upsettingboy/flatpak-lol/) (my own `flatpak-lol`) something similar.

I don't know the inners of Garena, but the standard version is fully working and with no performance impact!! Great times ahead!
