### ISSUE TITLE
[Request] osu!

### ISSUE THREAD

**Issue by Oreeeee** [bottlesdevs/programs#61]
Lutris install scripts are availible on Lutris website. After installing dependencies the game throws an error that .NET Framework is missing, but it is installed.

**Comment by mirkobrombin** [comment]
Please post the lutris script too

**Comment by Oreeeee** [comment]
Here is a Lutris script: https://lutris.net/games/install/3548/view

**Comment by Oreeeee** [comment]
I managed to install osu! by installing .NET from winetricks. There might be something that winetricks does that Bottles doesn't do.

**Comment by mirkobrombin** [comment]
Just found this https://osu.ppy.sh/community/forums/topics/1576494?n=1

**Comment by Oreeeee** [comment]
I still had to install .NET from winetricks, otherwise I get this error:

gamemodeauto: 
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0120:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"osu!.exe" cannot be loaded
0120:err:module:LdrInitializeThunk Importing dlls for L"C:\\users\\----\\AppData\\Local\\osu!\\osu!.exe" failed, status c0000135

**Comment by jannuary** [comment]
[*cough*](https://flathub.org/apps/details/sh.ppy.osu)

**Comment by Oreeeee** [comment]
Fixed by #172
