### ISSUE TITLE
[Mini feature request] Add new installers or customize existing ones

### ISSUE THREAD

**Issue by Sevenseraphim** [bottlesdevs/programs#68]
Hi, I would just like to request if its possible to edit existing installers or even add new ones...

I haven't been able to figure out how to do that although I can read the "manifest" and edit the lines it doesn't save it when I try installing the program after making the required changes.

My primary reason for wanting to do this is to install the latest version of gog since updating gog from the program itself always fails for some reason.

I want to change the following lines in the gog installer from:
  **file_name: setup_galaxy_2.0.45.61.exe
  url: https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.45.61/setup_galaxy_2.0.45.61.exe
  file_checksum: 5d2ae5367f72b3a23728bb8732e6df4e**

to:
  **file_name: setup_galaxy_2.0.50.34.exe
  url: https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.50.34/setup_galaxy_2.0.50.34.exe
  file_checksum: 7e58c84138d8007044da9c6a6f8a1d58**

Thanks for making bottles such an easy to use wine manager. Cheers! 🍷

**Comment by mirkobrombin** [comment]
Hi, thanks for the kind words.

To contribute or edit installers you have to use a local repository. Take a look at our documentation for maintainers: https://maintainers.usebottles.com/

**Comment by Sevenseraphim** [comment]
Oooh.. ok. After doing a lot of reading I just realised that the yaml installation files are not actually on the user's computer but rather they're accessed from github which is why we need to git clone the repository first to have local access to the files and manually test out the new installers before opening a PR to modify them. (I hope I understood this right?)

Actually what I was requesting was for the end user to be able to edit a manifest before running it locally since we can see and edit the manifest but there is no way to save it temporarily before running it... for example maybe an end user wants to make a small modification to the installer that suits their own particular usecase but is not suitable for everyone else and therefore it wouldn't make sense for them to open a PR for it...

Maybe like a "+" sign to make new installers locally or an "edit" option before running the installer? 

(note: thank you to Dansito for making a PR to update the gog client :)

**Comment by mirkobrombin** [comment]
You understand it correctly. Btw implementing what you are asking for is a very time consuming task and need to change how Bottles handle repositories. We will evaluate this, thanks for reporting
