### ISSUE TITLE
battle.net wont connect online

### ISSUE THREAD

**Issue by 10leej** [bottlesdevs/programs#70]
Error Code

![image](https://user-images.githubusercontent.com/2258333/169866535-76bdbf33-7497-45ab-a8e1-4b31238f9b46.png)

https://us.battle.net/support/en/article/13875

Application does install via the installer script, but wont allow you to connect online, you get this error when you launch and focus the application.

[error.txt](https://github.com/bottlesdevs/programs/files/8756491/error.txt)

**Comment by jkvargas** [comment]
same for me, it keeps updating files and then this errror comes up.
