### ISSUE TITLE
Ubisoft Connect doesn't launch

### ISSUE THREAD

**Issue by redromnon** [bottlesdevs/programs#77]
## Bug Description
I have created a Gaming-environment Bottle and Ubisoft Connect has sucessfully installed via the Installers section.

But the application fails to launch despite waiting for quite some time, restarting, killing all processes and even creating a new Bottle. The terminal doesn't show any fatal errors except this - `002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).`

All I can see is a transparent window with a border.

![Bottles_UbisoftBug](https://user-images.githubusercontent.com/74495920/171438169-e9a5b725-e403-45b0-a250-7d49b457f8f8.png)

## System

Pop OS 22.04
Flatpak version

**Comment by stef942** [comment]
hi, i have exactly the same problem : transparent window afer lauch and same error message :+1: 

`002c:err:wineboot:process_run_key`` Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0110:err:module:hacks_init HACK: Simulating sched quantum in `fsync.`

**Comment by mirkobrombin** [comment]
Try using an old version of Caffe please

**Comment by redromnon** [comment]
As advised I've tried caffe-7.0 and 6.23. Still get the same transparent window and wineboot error. No improvements.
![Bottles_UbisoftBug2](https://user-images.githubusercontent.com/74495920/172783851-c94a720c-3717-47bf-8ed0-dff8b66b710e.png)

**Comment by stef942** [comment]
tried 7.4 and 6.23 and also still same errors

**Comment by MinecraftPlaye** [comment]
I can confirm this problem:

```
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0110:err:module:hacks_init HACK: Simulating sched quantum in fsync.
0110:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0110:err:winediag:gnutls_process_attach Compiled without DH support.
```

The problem persists when enabling or disabling Bottles runtime and/or GameMode.

```
caffe-7.5 (or sys-wine-7.0)
dxvk-1.10.1
vkd3d-proton-2.6
dxvk-nvapi-v0.5.3
```

I also tried to test it with caffe-7.7.
```
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0110:err:module:hacks_init HACK: Simulating sched quantum in fsync.
```

OS version is set to Windows 10 and I'm using 2022.5.28-trento-3 (flatpak version) on Manjaro with AMD mesa drivers.

**Comment by TheFlagCourier** [comment]
Experiencing similar results using the following configuration: [backup_ubsoft-proton.yml.txt](https://github.com/bottlesdevs/programs/files/8937479/backup_ubsoft-proton.yml.txt)

- OS: _Fedora 36 (Fedora's Kernel 5.18.5-200.fc36.x86_64)_
- DE: _Gnome 42.2_
- Windowing System: _Wayland **&** X11 (Tested Independently)_
- GPU: _AMD Radeon™ VII_
- CPU: _AMD Ryzen™ 7 2700X_

#### Workaround
Changing the runner from `Caffe-7.7` to `GE Proton 7.10` will allow Ubisoft Connect to load properly after around 5 seconds.

**Comment by mirkobrombin** [comment]
I'm able to launch, login, install/play games using Caffe 7.10-1

**Comment by redromnon** [comment]
I can confirm it works with Caffe 7.10-1 - was able to login, install and the play a game. But after restaing my PC, the game I installed doesn't show up under _Programs_ and Ubisoft Connect asks me to login again. This happened when I switched back from Wine GE to Caffe 7.10-1
