### ISSUE TITLE
Origin installation is mega slow with esync but not with system

### ISSUE THREAD

**Issue by yodatak** [bottlesdevs/programs#85]
Hi on Fedora 36 flatpak version of Bottle i create a new game prefix and after origin is supper slow and don't show up only after 10 min but when i changed the syncronisation in preference to system it run smoothy.

Any problem with Fedora or Botlle or Origin ?

**Comment by mirkobrombin** [comment]
This is strictly related to Wine and (maybe) your system. I suggest you to switch to fsync or futex2 instead.
