### ISSUE TITLE
Add GOG GALAXY 2.0 launcher

### ISSUE THREAD

**Issue by Marckniack** [bottlesdevs/programs#9]
Official link: [https://www.gog.com/galaxy](https://www.gog.com/galaxy)
WineHQ: [https://appdb.winehq.org/objectManager.php?sClass=version&iId=38672](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38672)

**Comment by mirkobrombin** [comment]
Installer provided.
Review: https://github.com/bottlesdevs/programs/blob/main/Reviews/gog.md
