### ISSUE TITLE
Tried Installing PhraseExpress Text Expander but it shows same error everytime

### ISSUE THREAD

**Issue by thorrrr** [bottlesdevs/programs#97]
HI I just wanted to use PhraseExpress in Linux via Botles i have the exe on my desktop it runs right to end then errors  with the following

https://i.imgur.com/RVgD9Cc.png

Any ideas how  to fix it  and i canhardly see it due to hight screen resolution

**Comment by mirkobrombin** [comment]
Hi did you check on winedb?
The resolution is a common wine problem, a workaround is enabling wine window decorations via winecfg

**Comment by thorrrr** [comment]
Hi Mirko
Yes I cannot find it which I find strange as a textexpander.
Unless I am searching wrong or you need to be a member.
Just getting into Linux and it only thing I need besides Excel

**Comment by mirkobrombin** [comment]
Seems like no one had luck on this

**Comment by thorrrr** [comment]
Why have you seen people try?

**Comment by mirkobrombin** [comment]
I mean, there are no results online so probably no one tried or had no luck.

**Comment by thorrrr** [comment]
Cheers Is it easy to remove bottles and is it in the docs ?

**Comment by mirkobrombin** [comment]
flatpak remove bottles
